name: Deploy to Public Repository

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        # No need to specify repository here since we're checking out the current repo
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
        
      - name: Deploy to public repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          repository-name: KodeMinds-Global/opulent-travels-public 
          branch: main
          git-config-name: GitHub Actions
          git-config-email: github-actions@github.com
          clean: true 