name: Update GitHub Pages Visibility

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed

jobs:
  update-pages-visibility:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Make GitHub Pages public
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.updateInformationAboutPagesSite({
              owner: context.repo.owner,
              repo: context.repo.repo,
              public: true
            }); 